### ISSUE TITLE
[feature] Config file support for preconfigured scans

### ISSUE THREAD

**Issue by bauthard** [projectdiscovery/naabu#77]
**Describe the solution you'd like**

A config file allowing users to set custom rules for different kinds of scans, so instead of feeding multiple CLI, users can simply provide a config file to perform a custom scan. 

Subfinder make use of config file `$HOME/.config/subfinder/config.yaml`, same can be done for naabu as well `$HOME/.config/naabu/config.yaml`

Example of the config file:- 

```yaml

# Host to scans

host:
    - uber.com
    - 1.1.1.1
    - 192.168.1.0/24

# OR 

host:
    - uber.com, 1.1.1.1, 192.168.1.0/24

# Full port scan
p:
    - '-'

# Custom list of ports to scan
p:
    - '20,30,45,100-200,400'

# Top ports to scan
top-ports:
    - 100

# Exclude CDN full port scan. 
exclude-cdn:
    - true

# List to hosts to exclude from the scan
exclude-hosts:
    - 192.168.0.1, 192.168.0.2, 192.168.0.3, 127.0.0.1

# OR 

exclude-hosts:
    - 192.168.0.1
    - 192.168.0.2
    - 192.168.0.3
    - 192.168.0.4

# List to ports to exclude from the scan
exclude-ports: 
    - 25, 21, 22

# OR 

exclude-ports: 
    - 25
    - 21
    - 22
```

In this way, one can define all configurable flags using the config files. 

**Suggested flag:- `config`**

Example:- 

```sh
naabu -iL hosts.txt -config config.yaml
```
